plugins {
    id 'java'
    id 'checkstyle'
    id 'application'
    id 'com.github.spotbugs' version '5.0.14'
}

group = 'edu.sandiego.comp305'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

checkstyle {
    ignoreFailures = false
}

spotbugs {
    ignoreFailures = false
}

application {
    mainClass = 'edu.sandiego.comp305.StringUtils'
}

test {
    useJUnitPlatform()
    mustRunAfter spotbugsMain
    mustRunAfter spotbugsTest
}